language: python
python:
 - "3.6"
script :
    - sudo apt-get install -y portaudio19-dev
install: pip3 install -r requirements.txt
script:
  - sh run_travis.sh
  - coverage run --source=PLNFinalWork setup.py test
after_success: coveralls
